version: '2'


services:
    web_app:
        image: juanpablodaza/roundrobinserver
        container_name: roundrobbinserver
        ports:
            - "36000:4568"
    web_service1:
        image: juanpablodaza/logservice
        container_name: logservice1
        ports:
            - "36001:4567"
    web_service2:
        image: juanpablodaza/logservice
        container_name: logservice2
        ports:
            - "36002:4567"
    web_service3:
        image: juanpablodaza/logservice
        container_name: logservice3
        ports:
            - "36003:4567"
    db:
        image: mongo:3.6.1
        container_name: db
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - 27017:27017
        command: mongod
        
volumes:
    mongodb:
    mongodb_config: